# Generated by Django 3.2.15 on 2022-10-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BootcampNextDate12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_bootcamp', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookBootcamp12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('bootcamp_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_date', to='booking.bootcampnextdate12')),
            ],
            options={
                'unique_together': {('name', 'bootcamp_date')},
            },
        ),
    ]
