# Generated by Django 3.2.15 on 2022-10-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingbootcamp',
            name='bootcamp_date',
            field=models.DateField(null=True),
        ),
    ]
