# Generated by Django 3.2.15 on 2022-10-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootcamp',
            name='bootcamp_title',
        ),
        migrations.RemoveField(
            model_name='bootcamp',
            name='slug',
        ),
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
