# Generated by Django 3.2.15 on 2022-10-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20221008_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='bootcamp_date',
            field=models.CharField(choices=[('November', 'November'), ('December', 'December'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April')], default='', max_length=10),
        ),
    ]
