# Generated by Django 3.2.15 on 2022-10-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bootcamp_bootcamp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='user',
        ),
    ]
