# Generated by Django 3.2.15 on 2022-10-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_signup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='bootcamp_date',
            field=models.CharField(choices=[('November', 'November'), ('December', 'December'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April')], default='Select a month', max_length=10),
        ),
    ]
