# Generated by Django 3.2.15 on 2022-10-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_bootcamp_bootcamp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='bootcamp_date',
            field=models.CharField(choices=[('November', 'November'), ('December', 'December'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
