# Generated by Django 3.2.15 on 2022-10-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20221009_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='bootcamp',
        ),
        migrations.AddField(
            model_name='signup',
            name='bootcamp_date',
            field=models.CharField(choices=[('November', 'November'), ('December', 'December'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April')], default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Bootcamp',
        ),
    ]
